# -*- coding: utf-8 -*-
"""Entrar SISAGUA Automatico_GAL-Nao Validado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1icMp23O79UkmB-wIna6rMiFpTkovpCCb
"""

!pip3 install -U selenium
!pip3 install webdriver-manager
!pip3 install pyvirtualdisplay
!apt-get update # to update ubuntu to correctly run apt install
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import Select
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import time
import os

from selenium.webdriver.chrome.options import Options

!pip install datetime
from datetime import date

from google.colab import drive

drive.mount('/content/drive')

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

chrome_options = Options()

chrome_options.add_argument("start-maximized")
chrome_options.add_argument("enable-automation")
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-infobars")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--disable-browser-side-navigation")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--force-device-scale-factor=1")

ser = Service()

wd = webdriver.Chrome(service=ser, options=chrome_options)

#ATRIBUIR CADA XPATH DE CADA CRS A UMA VARIÁVEL
CRS_01 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[2]/td'
CRS_02 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[12]/td' 
CRS_03 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[13]/td'
CRS_04 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[14]/td'
CRS_05 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[15]/td'
CRS_06 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[16]/td'
CRS_07 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[17]/td'
CRS_08 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[18]/td'
CRS_09 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[19]/td'
CRS_10 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[3]/td'
CRS_11 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[4]/td'
CRS_12 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[5]/td'
CRS_13 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[6]/td'
CRS_14 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[7]/td'
CRS_15 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[8]/td'
CRS_16 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[9]/td'
CRS_17 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[10]/td'
CRS_18 = '//*[@id="idRegionalSaudeSisagua_panel"]/div[2]/table/tbody/tr[11]/td'

#ATRIBUIR CADA CSS DE CADA MÊS A UMA VARIÁVEL
#janeiro = '#mesColeta > tbody > tr:nth-child(1) > td:nth-child(1) > div > div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default'
#fevereiro = '#mesColeta > tbody > tr:nth-child(1) > td:nth-child(3) > div > div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default'
#marco = '#mesColeta > tbody > tr:nth-child(1) > td:nth-child(5) > div > div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default'
#abril = '#mesColeta > tbody > tr:nth-child(1) > td:nth-child(7) > div > div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default'
#maio = '#mesColeta > tbody > tr:nth-child(1) > td:nth-child(9) > div > div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default'
#junho = '#mesColeta > tbody > tr:nth-child(2) > td:nth-child(1) > div > div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default'
#julho = '#mesColeta > tbody > tr:nth-child(2) > td:nth-child(3) > div > div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default' 
#agosto = '#mesColeta > tbody > tr:nth-child(2) > td:nth-child(5) > div > div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default'
#setembro = '#mesColeta > tbody > tr:nth-child(2) > td:nth-child(7) > div > div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default'
#outubro = '#mesColeta > tbody > tr:nth-child(2) > td:nth-child(9) > div > div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default'
#novembro = '#mesColeta > tbody > tr:nth-child(3) > td:nth-child(1) > div > div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default'
#dezembro = '#mesColeta > tbody > tr:nth-child(3) > td:nth-child(3) > div > div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default'

#CRIAR LISTA DAS VARIAVEIS XPATH CRS
lista_crs = [CRS_01, CRS_02, CRS_03, CRS_04, CRS_05, CRS_06, CRS_07, CRS_08, CRS_09, CRS_10, CRS_11, CRS_12, CRS_13, CRS_14, CRS_15, CRS_16, CRS_17, CRS_18]

lista_crs_nomes = ['01 CRS', '02 CRS', '03 CRS', '04 CRS', '05 CRS', '06 CRS', '07 CRS', '08 CRS', '09 CRS', '10 CRS', '11 CRS', '12 CRS', '13 CRS', '14 CRS', '15 CRS', '16 CRS', '17 CRS', '18 CRS']

#CRIAR LISTA DAS VARIAVEIS XPATH MESES
#lista_meses = [janeiro, fevereiro, marco, abril, maio, junho, julho, agosto, setembro, outubro, novembro, dezembro]
#lista_meses_nomes = ['janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro']

import pandas as pd

wd.get('http://sisagua.saude.gov.br/sisagua/login.jsf')

from time import sleep

action = webdriver.ActionChains(wd)

usuario = '03036108084'
senha = 'Yurigp16@'

sleep(5)
campo_usuario = wd.find_element(By.CSS_SELECTOR, '#email')
sleep(1)
campo_usuario.send_keys(usuario)
  
campo_senha = wd.find_element(By.CSS_SELECTOR, '#senha')
sleep(1)
campo_senha.send_keys(senha)
  
botao_entrar = wd.find_element(By.CSS_SELECTOR, '#btnEntrar > span')
sleep(0.5)
botao_entrar.click()
sleep(20)

from time import time

wait = WebDriverWait(wd, timeout=1000)
today = date.today()
d1 = today.strftime("%d-%m-%Y")

for i,j in zip(lista_crs, lista_crs_nomes):
    sleep(5)
    pagina_inicial = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#box_menu_top > ul > li.paginainicial > a')))
    sleep(1)
    pagina_inicial.click()
    sleep(4)

    relatorios = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#menu > ul > li:nth-child(5) > a > span.ui-menuitem-text')))
    sleep(3)
    action.move_to_element(relatorios).perform()
    sleep(3)

    acompanhamento_vigilancia = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#menu > ul > li.ui-widget.ui-menuitem.ui-corner-all.ui-menu-parent.ui-menuitem-active > ul > li:nth-child(7) > a > span')))
    acompanhamento_vigilancia.click()
    sleep(10)

    # SELECIONAR ABRANGÊNCIA
    abrangencia = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#idAbrangencia > div.ui-selectonemenu-trigger.ui-state-default.ui-corner-right > span')))
    action.move_to_element(abrangencia).perform()
    sleep(2)
    abrangencia.click()
    sleep(4)

    # SELECIONAR A LISTA SUSPENSA 'REGIONAL DE SAÚDE'
    regional_saude = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#idAbrangencia_panel > div > ul > li:nth-child(3)')))
    action.move_to_element(regional_saude).perform()
    sleep(2)
    regional_saude.click()
    sleep(4)

    # SELECIONAR LISTA SUSPENSA PARA ESCOLHER POR CRS
    escolha_CRS = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#idRegionalSaudeSisagua_label')))
    action.move_to_element(escolha_CRS).perform()
    sleep(2)
    escolha_CRS.click()
    sleep(4)

    # SELECIONAR CRS
    CRS_X = wait.until(EC.presence_of_element_located((By.XPATH, i))).click()
    sleep(4)

    # SELECIONAR BOX GAL_NAO_VALIDADA
    gal_nao_validada = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#situacao > tbody > tr:nth-child(1) > td:nth-child(3) > div > div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default')))
    action.move_to_element(gal_nao_validada).perform()
    sleep(2)
    gal_nao_validada.click()
    sleep(4)

    # SELECIONAR MÊS ESPECÍFICO
    mes_todos = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#filtroConsulta > fieldset > div:nth-child(4) > table:nth-child(2) > tbody > tr > td:nth-child(1) > div > div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default")))
    action.move_to_element(mes_todos).perform()
    sleep(2)
    mes_todos.click()
    sleep(4)

    # CLICAR EM PESQUISAR
    pesquisar = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#btConsultar > span')))
    action.move_to_element(pesquisar).perform()
    sleep(2)
    pesquisar.click()
    sleep(4)

    try:  
      # GERAR O RELATÓRIO
        gerar_relatorio = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#imprimirLista')))
        action.move_to_element(gerar_relatorio).perform()
        sleep(2)
        gerar_relatorio.click()
        sleep(5)
    except Exception as e:
        print(e)
        sleep(2)
    finally:
        sleep(20)
        if os.path.exists('/content/relatorioAcompanhamentoAmostrasVigilancia.xlsx') == True:      
          os.rename('/content/relatorioAcompanhamentoAmostrasVigilancia.xlsx', '/content/'+j+': Download em '+d1+'.xlsx')
          print(j+' -'+' PRONTO!')
          sleep(1)
          wd.refresh()
          sleep(3)
        else:
          print(j+'-'+' SEM DADOS!')
wd.quit()

for i in sorted(os.listdir('/content/')):
  try:
    dados_5 = pd.read_excel('/content/'+i, header=5).dropna()
    dados_6 = pd.read_excel('/content/'+i, header=6).dropna()
    referencia = pd.read_excel('/content/drive/MyDrive/VIGIAGUA/18. GAL/Referencia codigo gal municipios.xlsx').drop(['Número da amostra', 'Código IBGE'], axis=1)
    if dados_5.columns[0].strip() == 'Data de Registro':
      filtro_nao_val = dados_5['Situação'] == 'GAL(Integração) - Não validada'
      dados_5_filtrado = dados_5[filtro_nao_val]
      dados_5_filtrado['Nº da Solicitação/Nº da Amostra'] = dados_5_filtrado['Nº da Solicitação/Nº da Amostra'].astype(int).astype(str)
      dados_5_filtrado['cod_municipio_gal']=dados_5_filtrado['Nº da Solicitação/Nº da Amostra'].str.slice(2, 8)
      tabela = pd.merge(dados_5_filtrado, referencia, on='cod_municipio_gal', how='left')
      tabela = tabela.drop('cod_municipio_gal', axis=1)
      tabela.to_excel(i.split('.')[0]+' - AMOSTRAS GAL NAO VALIDADAS.xlsx', index=False)
      print(i+' - PRONTO')
    else:
      filtro_nao_val = dados_6['Situação'] == 'GAL(Integração) - Não validada'
      dados_6_filtrado = dados_6[filtro_nao_val]
      dados_6_filtrado['Nº da Solicitação/Nº da Amostra'] = dados_6_filtrado['Nº da Solicitação/Nº da Amostra'].astype(int).astype(str)
      dados_6_filtrado['cod_municipio_gal']=dados_6_filtrado['Nº da Solicitação/Nº da Amostra'].str.slice(2, 8)
      tabela = pd.merge(dados_6_filtrado, referencia, on='cod_municipio_gal', how='left')
      tabela = tabela.drop('cod_municipio_gal', axis=1)
      tabela.to_excel(i.split('.')[0]+' - AMOSTRAS GAL NAO VALIDADAS.xlsx', index=False)
      print(i+' - PRONTO')
  except Exception as e:
    print(e)
    pass

from datetime import datetime

today = date.today()
d1 = today.strftime("%d-%m-%Y")
for j in lista_crs_nomes:
  #print(j)
  tabela_geral = pd.DataFrame()
  for i in sorted(os.listdir('/content/')):

    #print(i)
    try:
      if (i.split(' - ')[1] == 'AMOSTRAS GAL NAO VALIDADAS.xlsx')&(i.split(':')[0] == j):
        dados = pd.read_excel('/content/'+i)
        tabela_geral = pd.concat([dados, tabela_geral])
    except:
      pass
  if len(tabela_geral) != 0:
    tabela_geral['Nº da Solicitação/Nº da Amostra'] = tabela_geral['Nº da Solicitação/Nº da Amostra'].astype(int).astype(str)
    tabela_geral.to_excel(j+'_Download em - '+d1+'.xlsx', index=False)

emails_crs = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vSxKEO4dRHQll7HFDYPuGuyzG4jYBB7NQtxGV6Rvk01RfcX2qgkmxO-Amd0FFhACQ/pub?gid=2012216461&single=true&output=csv')

arquivos_enviar = []
for crs in lista_crs_nomes:
  for arquivo in sorted(os.listdir('/content/')):
    if (arquivo.split('_')[0] == crs):
      caminho_arquivo = '/content/' + arquivo
      arquivos_enviar.append(caminho_arquivo)

df_emails=pd.DataFrame()
for i in arquivos_enviar:
  crs=i.split('_')[0][-6:]
  lista_email_enviar = emails_crs[emails_crs['CRS']==crs]
  lista_email_enviar['arquivo'] = i
  df_emails = pd.concat([df_emails,lista_email_enviar])
df_emails = df_emails[['E-MAIL','arquivo']].reset_index(drop=True)
df_emails

lista_email_enviar = df_emails['E-MAIL'].to_list()
arquivos_enviar = df_emails['arquivo'].to_list()

import smtplib
import email.message

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

def enviar_emails_gmail():
  today = date.today()
  data_hoje = today.strftime("%d/%m/%Y")
  for i, j in zip(lista_email_enviar, arquivos_enviar):
    corpo_email = """
    Olá!
    Esse email é automatico.
    Foram retiradas, do Sisagua, as amostras não validadas pelos municípios da sua CRS.
    Segue, em anexo, o arquivo excel com as amostras não validadas de 2022 dos municípios da sua CRS.

    Estamos à disposição para qualquer dúvida.
    
    Atenciosamente,
    
    André Jarenkow
    Engenheiro Químico - Especialista em Saúde
    CRQ 05303444
    Equipe Vigiagua/CEVS
    (51) 3901-1126
    """
    fromaddr = "vigiaguacevs@gmail.com"
    toaddr = i
    
    # instance of MIMEMultipart
    msg = MIMEMultipart()
      
    # storing the senders email address  
    msg['From'] = fromaddr
      
    # storing the receivers email address 
    msg['To'] = toaddr
      
    # storing the subject 
    msg['Subject'] = "Amostras não validadas Sisagua-GAL: " + data_hoje
      
    # attach the body with the msg instance
    msg.attach(MIMEText(corpo_email, 'plain'))
      
    # open the file to be sent 
    filename = j.split('content/')[1]
    attachment = open(j, "rb")
      
    # instance of MIMEBase and named as p
    p = MIMEBase('application', 'octet-stream')
      
    # To change the payload into encoded form
    p.set_payload((attachment).read())
      
    # encode into base64
    encoders.encode_base64(p)
      
    p.add_header('Content-Disposition', "attachment; filename= %s" % filename)
      
    # attach the instance 'p' to instance 'msg'
    msg.attach(p)
      
    # creates SMTP session
    s = smtplib.SMTP('smtp.gmail.com', 587)
    s.starttls()
    s.ehlo 
      
    # Authentication
    s.login(fromaddr, "ovoavxcjoxhfyqad")
      
    # Converts the Multipart msg into a string
    text = msg.as_string()
      
    # sending the mail
    s.sendmail(fromaddr, toaddr, text)
      
    # terminating the session
    s.quit()
    print('E-mail para '+i+' Enviado!')

enviar_emails_gmail()